# Unique name for this workflow
name: CI

# Definition when the workflow should run
on:
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'
    paths-ignore:
      - 'sfdx-project.json'
      - 'README.md'

# Jobs to be executed
jobs:
  validate:
    runs-on: Ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - name: 'Validate on Production'
        uses: jawills/sf-deploy@v1.0
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL}}
          DRY_RUN: true